# vim: set ts=4 sw=2 tw=0 et :
---

- name: zsh config
  import_tasks: zsh.yml
  when: zsh_enabled
  tags:
    - shell
    - zsh

- name: SSH agent
  import_tasks: ssh_agent.yml
  tags:
    - shell

- name: ntfy
  import_tasks: ntfy.yml
  tags:
    - ntfy
    - shell
