# vim: set ts=4 sw=2 tw=0 et :
---

- name: zsh config
  import_tasks: zsh.yml
  when: zsh_enabled
  tags:
    - shell
    - zsh

- name: SSH agent
  import_tasks: ssh_agent.yml
  tags:
    - shell

- name: ntfy
  import_tasks: ntfy.yml
  tags:
    - ntfy
    - shell

- name: Install tmux config
  import_tasks: tmux.yml
  tags:
    - tmux
    - shell

- name: Create gnome-terminal-server override dir
  file:
    path: "{{ ansible_user_dir }}/.config/systemd/user/gnome-terminal-server.service.d"
    state: directory
    recurse: yes

- name: Install gnome-terminal-server override
  copy:
    src: gnome-terminal-server-override.conf
    dest: "{{ ansible_user_dir }}/.config/systemd/user/gnome-terminal-server.service.d/override.conf"
