# vim: set ts=4 sw=2 tw=0 et :
---

- name: Install zsh with Pacman
  pacman:
    name:
      - zsh
      - zsh-completions
      - zsh-syntax-highlighting
    state: present
  become: yes
  when: use_sudo and ansible_distribution == "Archlinux"

- name: Copy zsh dir
  copy:
    src: zsh/
    dest: "{{ ansible_user_dir }}/.zsh"

- name: Install zshrc
  template:
    src: zsh/zshrc.j2
    dest: "{{ ansible_user_dir }}/.zshrc"
    mode: 0640

- name: Set up shell
  expect:
    command: "chsh -s /usr/bin/zsh"
    responses:
      (?i)password: "{{ ansible_become_pass }}"
  when: ansible_user_shell != "/bin/zsh"

- name: Download rushlink command
  get_url:
    url: https://gitea.hashru.nl/dsprenkels/rushlink/raw/branch/master/contrib/rushlink
    dest: "{{ ansible_user_dir }}/.local/bin/rushlink"
    force: yes
    mode: "0755"
