# vim: set ts=4 sw=2 tw=0 et :
---

- name: Install zsh with Pacman
  pacman:
    name:
      - zsh
      - zsh-completions
      - zsh-syntax-highlighting
    state: present
  become: yes
  when: use_sudo and ansible_distribution == "Archlinux"

- name: Copy zsh dir
  copy:
    src: zsh/
    dest: "{{ ansible_user_dir }}/.zsh"

- name: Create zsh dirs
  file:
    state: directory
    path: "{{ ansible_user_dir }}/{{ item }}"
  loop:
    - ".zsh"
    - ".zsh/completions"

- name: Install zshrc
  template:
    src: zsh/zshrc.j2
    dest: "{{ ansible_user_dir }}/.zshrc"
    mode: 0640

- name: Set up shell
  expect:
    command: "chsh -s /usr/bin/zsh"
    responses:
      (?i)password: "{{ ansible_become_pass }}"
  when: ansible_user_shell != "/bin/zsh"
