language: python
sudo: false

install:
    - pip install ansible

before_script:
    - echo move host vars out of the way
    - mv host_vars bla
    - mv group_vars bla
    - echo "hi" > private_vault_pw.key

script:
    - ansible-playbook --syntax-check *.yml
