#  vim: set ts=2 sw=2 tw=0 et :
---

- hosts: own_machines
  become: no
  roles:
    - arch
    - tools

- hosts: powerline
  become: no
  roles:
    - powerline

- hosts: all
  become: no
  roles:
    - shell
    - gnupg
    - git
    - vim

- hosts: desktop
  roles:
    - i3
