#  vim: set ts=2 sw=2 tw=0 et :
---

- hosts: all
  roles:
    - common
    - ssh_client

- hosts: own_machines
  become: no
  roles:
    - arch
    - tools

- hosts: powerline
  become: no
  roles:
    - powerline

- hosts: all
  become: no
  roles:
    - shell
    - gnupg
    - git
    - vim

- hosts: distcc
  become: yes
  roles:
    - distcc_armv7
  tags:
    - distcc

- hosts: vpn
  become: no
  roles:
    - vpn
    - sshd
