---
- hosts: archlinux
  become: yes
  tasks:
    - name: Run pacman -Syu
      pacman:
        update_cache: yes
        upgrade: yes
    - name: Run Topgrade for local stuff
      command: topgrade --only vim gem rustup cargo flutter go pipx tlmgr
      when: ansible_machine == "x86_64"
    - name: Figure out local hostname
      local_action: command hostname
      run_once: true
      become: no
      register: output
      changed_when: false
    - name: Reboot hosts
      reboot:
      when: inventory_hostname not in output.stdout and inventory_hostname != 'archeron'

- hosts: archeron
  become: yes
  tasks:
    - name: Reboot VPN host archeron
      reboot:

- hosts: archeron
  become: yes
  tasks:
    - docker_compose:
        project_src: "/etc/containers/{{ item }}"
        pull: yes
      loop:
        - "matomo"
        - "nextcloud"
  tags:
    - docker-update
