---

- block:

    - name: Install powerline globally on Arch iff sudo
      import_tasks: powerline-global-arch.yml
      become: yes
      when: ansible_distribution == "Archlinux" and use_sudo

    - name: Install powerline locally on other systems
      import_tasks: powerline-user.yml
      when: ansible_distribution != "Archlinux" or not use_sudo

    - name: Find powerline modules dir
      find_powerline:
      tags:
        - zsh

    - name: Make sure directories exist
      file:
        state: directory
        recurse: yes
        path: "{{ item }}"
      loop:
        - "{{ ansible_user_dir }}/.config/powerline"
        - "{{ ansible_user_dir }}/.config/systemd/user/"

    - name: Copy powerline configuration
      synchronize:
        src: config-powerline/
        dest: "{{ ansible_user_dir }}/.config/powerline"
        checksum: true

    - name: Install powerline-daemon systemd file
      copy:
        src: powerline-daemon.service
        dest: "{{ ansible_user_dir }}/.config/systemd/user/powerline-daemon.service"
      when: ansible_service_mgr == "systemd"

    - name: Enable powerline-daemon service
      systemd:
        name: powerline-daemon.service
        enabled: yes
        daemon_reload: yes
        user: yes
      when: ansible_service_mgr == "systemd"
  tags:
    - powerline
    - shell
