---

- name: Install backup script
  copy:
    src: "restic-backup.zsh"
    dest: "~/.zsh/lib/restic-backup.zsh"
    mode: "0700"
  tags:
    - backup

- name: Install backup source variables
  template:
    src: "restic_settings.zsh.j2"
    dest: "~/.local/lib/restic_settings.zsh"
    mode: "0700"
  tags:
    - backup

- name: Install systemd script
  copy:
    src: "do_backup.zsh"
    dest: "~/.local/lib/do_backup.zsh"
    mode: "0755"
  tags:
    - backup

- name: Install systemd units
  copy:
    src: "{{ item }}"
    dest: "~/.config/systemd/user/"
  loop:
    - "restic-backup.service"
    - "restic-backup.timer"
  tags:
    - backup

- name: Enable systemd units
  systemd:
    scope: user
    daemon_reload: yes
    enabled: yes
    name: restic-backup.timer
  tags:
    - backup
