# vim: set ts=4 sw=2 tw=0 et :
---

- name: Install i3 packages
  pacman:
    name: "{{ item }}"
    state: present
  become: yes
  with_items:
    - i3-wm
    - i3lock
    - i3status
    - dmenu
    - perl
