---

- name: Create workdir
  local_action:
    module: file
    path: work/vpn/ca
    state: directory
    mode: "0700"

- name: Generate CA private key
  local_action:
    module: openssl_privatekey
    path: work/vpn/ca/ca.key
    size: 4096
    cipher: aes256
    passphrase: "{{ lookup('passwordstore', 'ansible/vpn/ca_key create=True')}}"

- name: Generate CA Public Key
  local_action:
    module: openssl_publickey
    path: work/vpn/ca/ca.pub
    privatekey_path: work/vpn/ca/ca.key
    privatekey_passphrase: "{{ lookup('passwordstore', 'ansible/vpn/ca_key')}}"

- name: Generate CA Certificate CSR
  local_action:
    module: openssl_csr
    path: work/vpn/ca/ca.csr
    privatekey_path: work/vpn/ca/ca.key
    privatekey_passphrase: "{{ lookup('passwordstore', 'ansible/vpn/ca_key')}}"
    common_name: "VPN Certificate Authority"
    country_name: "NL"
    organization_name: "Thom Wiggers"
    organizational_unit_name: "Wiggers' Waarachtige Waarheidscertificaten"
    key_usage:
      - keyCertSign
      - cRLSign
    key_usage_critical: yes
    basic_constraints:
      - "CA:TRUE"
      - "pathLenConstraint:0"

- name: Self-Sign CA Certificate CSR
  local_action:
    module: openssl_certificate
    provider: selfsigned
    csr_path: work/vpn/ca/ca.csr
    privatekey_path: work/vpn/ca/ca.key
    privatekey_passphrase: "{{ lookup('passwordstore', 'ansible/vpn/ca_key')}}"
    path: work/vpn/ca/ca.crt

- name: Initialize serial file
  local_action:
    module: copy
    dest: work/vpn/serial
    content: "01\n"

- name: Create index.txt
  local_action:
    module: file
    path: "work/vpn/index.txt"
    state: touch

- name: Create directories
  local_action:
    module: file
    path: "work/vpn/{{ item }}"
    state: directory
  with_items:
    - issued
    - certs_by_serial
    - requests
