---

- name: Create directory for key material
  file:
    status: directory
    path: /etc/openvpn/keys
    mode: "0700"

- name: Create client private key
  openssl_privatekey:
    size: 4096
    path: /etc/openvpn/keys/client.key
    mode: "0700"

- name: Create client public key
  openssl_publickey:
    path: "/etc/openvpn/keys/client.pub"
    privatekey_path: "/etc/openvpn/keys/client.key"

- name: "Generate CSR for client {{inventory_hostname}}"
  openssl_csr:
    path: /etc/openvpn/keys/client.csr
    privatekey_path: /etc/openvpn/keys/client.key
    common_name: "{{ inventory_hostname }}"
    country_name: "NL"
    organization_name: "Thom Wiggers"
    subject_alt_name:
      - "{{ inventory_hostname }}"
    key_usage:
      - digitalSignature
      - keyEncipherment
    key_usage_critical: yes
    extended_key_usage:
      - clientAuth
    extended_key_usage_critical: yes
    basic_constraints:
      - "CA:FALSE"
  register: client_csr

- name: Fetch CSR
  fetch:
    src: /etc/openvpn/keys/client.csr
    dest: "work/vpn/requests/{{ inventory_hostname }}.csr"
    flat: true
  when: client_csr is changed

- name: Get certificate request signed
  import_tasks: sign-csr.yml
  when: client_csr is changed
  vars:
    role: client

- name: Fetch signed certificate
  copy:
    src: "work/vpn/requests/{{ inventory_hostname}}.csr"
    dest: "/etc/openvpn/keys/client.crt"

- name: Generate DH parameters
  openssl_dhparam:
    path: /etc/openvpn/dh4096.pem
    size: 4096

- name: Install configuration
  template:
    src: client.conf.j2
    dest: /etc/openvpn/client/client.conf

- name: Place CA material
  copy:
    src: "work/vpn/ca/ca.crt"
    dest: /etc/openvpn/keys/
