---

- name: Install Wireguard
  pacman:
    name:
      - wireguard-arch
      - wireguard-tools

- name: Install NetworkManager service
  pacman:
    name: networkmanager-openvpn
  when: networkmanager
