---

- name: Install DKMS wireguard
  pacman:
    name:
      - linux-raspberrypi-headers
      - wireguard-dkms
  when: ansible_machine != "x86_64"

- name: Install Wireguard tools
  pacman:
    name:
      - wireguard-tools
