---

- name: Install DKMS wireguard
  pacman:
    name:
      - linux-raspberrypi-headers
      - wireguard-dkms
  when: ansible_machine == "armv7l"

- name: Install Wireguard tools
  pacman:
    name:
      - wireguard-tools
