---

- name: Create directory for key material
  file:
    status: directory
    path: /etc/openvpn/keys
    mode: "0700"

- name: Create directory for ccd files
  file:
    status: directory
    path: /etc/openvpn/ccd
    owner: openvpn

- name: Create server private key
  openssl_privatekey:
    size: 4096
    path: /etc/openvpn/keys/server.key
    mode: "0700"
  notify:
    - restart openvpn server

- name: Create server public key
  openssl_publickey:
    path: "/etc/openvpn/keys/server.pub"
    privatekey_path: "/etc/openvpn/keys/server.key"
  notify:
    - restart openvpn server

- name: "Generate CSR for server {{inventory_hostname}}"
  openssl_csr:
    path: /etc/openvpn/keys/server.csr
    privatekey_path: /etc/openvpn/keys/server.key
    common_name: "{{ inventory_hostname }}"
    country_name: "NL"
    organization_name: "Thom Wiggers"
    subject_alt_name:
      - "{{ inventory_hostname }}"
    key_usage:
      - digitalSignature
      - keyEncipherment
    key_usage_critical: yes
    extended_key_usage:
      - serverAuth
    extended_key_usage_critical: yes
    basic_constraints:
      - "CA:FALSE"
  register: server_csr
  notify:
    - restart openvpn server

- name: Fetch CRL
  fetch:
    src: /etc/openvpn/keys/server.csr
    dest: "work/vpn/requests/{{ inventory_hostname }}.csr"
    flat: true
  when: server_crl is changed

- name: Get certificate request signed
  import_tasks: sign-csr.yml
  when: server_crl is changed
  vars:
    role: server

- name: Fetch signed certificate
  copy:
    src: "work/vpn/requests/{{ inventory_hostname}}.csr"
    dest: "/etc/openvpn/keys/server.crt"
  notify:
    - restart openvpn server

- name: Generate DH parameters
  openssl_dhparam:
    path: /etc/openvpn/dh4096.pem
    size: 4096
  notify:
    - restart openvpn server

- name: Install configuration
  template:
    src: server.conf.j2
    dest: /etc/openvpn/server.conf.j2
  notify:
    - restart openvpn server

- name: Place CA material
  copy:
    src: "work/vpn/ca/ca.crt"
    dest: /etc/openvpn/keys/
  notify:
    - restart openvpn server

- name: Enable systemd service
  systemd:
    name: "openvpn-server@server.conf"
    enabled: yes
