---

- name: "Randomize serial"
  local_action:
    module: command
    args:
      argv:
        - "openssl"
        - "rand"
        - "-hex"
        - "16"
  register: rand_output

- name: Check if serial exists
  local_action:
    module: command
    args:
      argv:
        - "openssl"
        - "ca"
        - "-config"
        - "roles/vpn/files/openssl.cnf"
        - "-status"
        - "{{ rand_output.stdout }}"
  changed_when: no
  failed_when: no
  register: status_output

- fail:
    msg: "Serial existed: {{ status_output.stderr }}"
  when:
    - '"not present in db" not in status_output.stderr'

- name: Write serial to file
  local_action:
    module: copy
    dest: work/vpn/serial
    content: "{{ rand_output.stdout }}"
  
- name: Generate certificate
  local_action:
    module: command
    args:
      argv:
        - 'openssl'
        - 'ca'
        - "-config"
        - "roles/vpn/files/openssl.cnf"
        - '-utf8'
        - '-batch'
        - '-in'
        - "work/vpn/requests/{{ inventory_hostname }}.csr"
        - '-out'
        - "work/vpn/issued/{{ inventory_hostname }}.csr"
        - "-outdir"
        - "work/vpn/certs_by_serial"
        - '-extfile'
        - "roles/vpn/files/{{ role }}-ext.cnf"
        - '-days'
        - '3650'
        - '-batch'
        - '-cert'
        - 'work/vpn/ca/ca.crt'
        - '-keyfile'
        - 'work/vpn/ca/ca.key'
        - '-passin'
        - "pass:{{ lookup('passwordstore', 'ansible/vpn/ca_key')}}"
