
- block:
  - name: Create pacman hooks folder
    file:
      state: directory
      path: /etc/pacman.d/hooks

  - name: Make sure pacman-contrib is installed
    pacman:
      name: pacman-contrib
      state: present

  - name: Insert hooks
    copy:
      src: "{{ item }}"
      dest: /etc/pacman.d/hooks
    loop:
      - paccache.hook
      - reflector.hook
  become: yes
  when: ansible_distribution == "Archlinux"
  tags:
    - arch
