
- block:
  - name: Place locale.gen
    copy:
      src: "locale.gen"
      dest: "/etc/locale.gen"
    register: locale_changed

  - name: Update locales
    command: locale-gen
    when: locale_changed.changed

  - name: Place locale.conf
    copy:
      src: "locale.conf"
      dest: "/etc/locale.conf"

  - block:
    - name: Create faillock config dir
      file:
        state: directory
        path: /etc/security/faillock.conf.d
        mode: "0755"

    - name: Place override file for faillock
      copy:
        src: 10-faillock_override.conf
        dest: /etc/security/faillock.conf.d/10-faillock_override.conf
        mode: "0644"
    tags:
      - faillock

  - name: Create pacman hooks folder
    file:
      state: directory
      path: /etc/pacman.d/hooks
      mode: "0755"

  - block:
    - name: Make sure required packages for paccache hook are installed
      pacman:
        name:
          - pacman-contrib
        state: present

    - name: Insert hook for paccache
      copy:
        src: "paccache.hook"
        dest: /etc/pacman.d/hooks
      loop:
    tags:
      - paccache

  - block:
    - name: Make sure required packages for reflector hook are installed
      pacman:
        name:
          - reflector
        state: present

    - name: Insert hooks
      copy:
        src: "reflector.hook"
        dest: /etc/pacman.d/hooks
    tags:
      - reflector
    when: ansible_machine == "x86_64"

  - name: Copy thomwiggers.gpg
    copy:
      src: "thomwiggers.gpg"
      dest: "{{ working_cache_dir }}/thomwiggers.gpg"

  - name: Add key to Pacman
    command: "pacman-key --add {{ working_cache_dir }}/thomwiggers.gpg"
    register: result
    changed_when: not "unchanged" in result.stdout

  - name: Trust key
    command: pacman-key --lsign-key 915D4ED34871E82F
    when: not "depth" in result.stdout

  - name: Include pacman configuration
    template:
      src: "pacman.conf.j2"
      dest: /etc/pacman.conf

  - name: Set up makepkg configuration
    template:
      src: "makepkg{% if ansible_machine == 'armv7l' %}_armv7{% endif %}.conf"
      dest: "/etc/makepkg.conf"

  become: yes
  when: ansible_distribution == "Archlinux"
  tags:
    - arch
