# vim: set ts=4 sw=2 tw=0 et :
---
- block:
  - name: Update pacman cache
    pacman:
      update_cache: yes
    become: yes

  - name: Install applications
    pacman:
      name: "{{ tools }}"
      state: "present"
    become: yes

  - name: Install tools for desktop use
    pacman:
      name: "{{ tools_desktop }}"
      state: "present"
    become: yes
    when: is_desktop|default(false)

  - name: Remove tools for desktop use from servers
    pacman:
      name: "{{ tools_desktop }}"
      state: absent
    become: yes
    when: not (is_desktop|default(false))

  - name: Remove programs
    pacman:
      name: "{{ removed_tools }}"
      state: "absent"
    become: yes

  - name: Copy topgrade configuration
    copy:
      src: topgrade.toml
      dest: "{{ ansible_user_dir }}/.config/topgrade.toml"

  tags:
    - tools
    - packages
    - install
  when: ansible_distribution == "Archlinux"
