# vim: set ts=4 sw=2 tw=0 et :
---
- block:
  - name: Update pacman cache
    pacman:
      update_cache: yes
    become: yes

  - name: Install applications
    pacman:
      name: "{{ tools }}"
      state: "present"
    become: yes

  - name: Install tools for desktop use
    pacman:
      name: "{{ tools_desktop }}"
      state: "present"
    become: yes
    when: is_desktop|default('false')

  - name: Remove programs marked absent
    pacman:
      name: "{{ removed_tools }}"
      state: "absent"
    become: yes

  tags:
    - tools
    - packages
    - install
  when: ansible_distribution == "Archlinux"
