- block:
  - name: Add SSH key for termius
    authorized_key:
      key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIDyyLu1Ejp68N0+hZBkVCxJ9+nLAWaHEhQiUmf/2lgQI Termius installed by Ansible"
      user: "{{ ansible_user }}"

  - name: Install SSH public keys
    authorized_key:
      key: "{{ item.value }}"
      user: "{{ ansible_user }}"
    loop: "{{ public_keys|dict2items }}"

  - name: Install SSH private key
    copy:
      content: "{{ ssh_private_key }}"
      mode: "0600"
      owner: "{{ ansible_user }}"
      dest: "{{ ansible_user }}/.ssh/id_ed25519"
    when: "ssh_private_key|default('') != ''"

  - name: Install SSH public key
    copy:
      content: "{{ public_keys[inventory_hostname] }}"
      mode: "0644"
      owner: "{{ ansible_user }}"
      dest: "{{ ansible_user }}/.ssh/id_ed25519.pub"
    when: "ssh_private_key|default('') != ''"

  tags:
    - ssh
