---
- block:
  - name: Install vim on Arch with sudo
    pacman:
      state: present
      name:
        - bash-language-server
        - rust-analyzer
        - texlab
        - python-jedi
        - "{{ vim_package|default('gvim') }}"
    become: yes
    when: use_sudo and ansible_distribution == "Archlinux"

  - name: Create vim folders
    file:
      state: directory
      dest: "{{ ansible_user_dir }}/{{ item }}"
    loop:
      - ".vim"
      - ".vim/undo"
      - ".vim/swaps"
      - ".vim/backups"
      - ".vim/bundle"

  - name: Copy vimrc
    template:
      src: "vimrc.j2"
      dest: "{{ ansible_user_dir }}/.vimrc"
    register: vimrc

  - name: Delete Vundle
    file:
      path: "{{ ansible_user_dir }}/.vim/bundle/Vundle.vim"
      state: absent
  tags:
    - vim

# vim: set ft=yaml.ansible ts=4 sw=2 tw=0 et :
