---
- block:
  - name: Install vim on Arch with sudo
    pacman:
      state: present
      name: "{{ vim_package|default('gvim') }}"
    become: yes
    when: use_sudo and ansible_distribution == "Archlinux"

  - name: Create vim folders
    file:
      state: directory
      dest: "{{ ansible_user_dir }}/{{ item }}"
    loop:
      - ".vim"
      - ".vim/undo"
      - ".vim/swaps"
      - ".vim/backups"
      - ".vim/bundle"

  - name: Copy vimrc
    template:
      src: "vimrc.j2"
      dest: "{{ ansible_user_dir }}/.vimrc"
    register: vimrc

  - name: Install Vundle
    git:
      repo: https://github.com/VundleVim/Vundle.vim.git
      dest: "{{ ansible_user_dir }}/.vim/bundle/Vundle.vim"
      update: yes
      depth: 1
  tags:
    - vim

# vim: set ft=yaml.ansible ts=4 sw=2 tw=0 et :
